version: '3'
services:
  tekxit:
    build:
      context: .
    container_name: mc-tekxit-docker
    environment:
      - VER=1.0.953
      - MEM=4G
    ports:
      - 25565:25565
    volumes:
      - "minecraft_data:/minecraft"
    restart: unless-stopped
volumes:
  minecraft_data:
