version: '3'
services:
  tekxit:
    build:
      context: .
    environment:
      - VERSION:"1.0.7.1"
      - MEM:"6G"
    ports:
      - 25565:25565
    volumes:
      - "./minecraft_data:/data"
    restart: unless-stopped
