version: '3'
services:
  tekxit:
    build:
      context: .
    environment:
      - VERSION:"1.0.950"
      - MEM:"4G"
    ports:
      - 25565:25565
    volumes:
      - "minecraft_data:/minecraft/tekxit"
    restart: unless-stopped

volumes:
  minecraft_data:
